from django.db import models
from usersadmon.models import AdmonUsuarios

class View_Master_Proveedor(models.Model):
    IDPendienteEnviar = models.IntegerField(primary_key=True)
    Folio = models.CharField(max_length=10, unique=True)
    NombreCortoCliente = models.CharField(max_length=100)
    NombreCortoProveedor = models.CharField(max_length=100)
    FechaDescarga = models.DateTimeField()
    Moneda = models.CharField(max_length=10)
    Status = models.CharField(max_length=15)
    IsEvidenciaDigital = models.BooleanField()
    IsEvidenciaFisica = models.BooleanField()
    Proyecto = models.CharField(max_length=30)
    TipoConcepto = models.CharField(max_length=30)
    IsControlDesk = models.BooleanField()
    SubtotalC = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    IVAC = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    RetencionC = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    TotalC = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    IsFacturaProveedor = models.BooleanField()
    FolioFactProveedor = models.CharField(max_length=50)
    StatusFacturaProveedor = models.CharField(max_length=50)
    SubtotalFacturaProveedor = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    IvaFacturaProveedor = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    RetencionFacturaProveedor = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    TotalFacturaProveedor = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    MOP = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    Subtotal = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    IVA = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    Retencion = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    Total = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    IsFacturaCliente = models.BooleanField()
    FolioFactCliente = models.CharField(max_length=50)
    StatusFacturaCliente = models.CharField(max_length=50)
    SubtotalFacturaCliente = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    IvaFacturaCliente = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    RetencionFactura = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    TotalFacturaCliente = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    IDProveedor = models.IntegerField(default=0)
    CostoSubtotalAnterior = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    CostoIVAAnterior = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    CostoRetencionAnterior = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    CostoTotalAnterior = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    NuevoCosto = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    NuevoCostoAccesorios = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    NuevoCostoRecoleccion = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    NuevoCostoRepartos = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    NuevoCostoSubtotal = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    NuevoCostoIVA = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    NuevoCostoRetencion = models.DecimalField(default=0, max_digits=30, decimal_places=5)
    NuevoCostoTotal = models.DecimalField(default=0, max_digits=30, decimal_places=5)

    class Meta:
        db_table = "View_Master_Proveedor"
        managed = False
