# Generated by Django 2.1.13 on 2020-01-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosCuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosxproveedor',
            name='Status',
            field=models.CharField(default='Activa', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDPagoxFactura',
            field=models.IntegerField(default=0),
        ),
    ]
