# Generated by Django 2.1.13 on 2019-12-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosCuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosxproveedor',
            name='Status',
            field=models.CharField(default='Pendiente', max_length=15),
            preserve_default=False,
        ),
    ]
