# Generated by Django 2.1.13 on 2019-12-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosCuenta', '0002_pagosxproveedor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDFactura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDPago',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDPagoxFactura',
            field=models.IntegerField(default=0),
        ),
    ]
