# Generated by Django 2.1.13 on 2020-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosCuenta', '0002_auto_20200106_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDProveedor',
        ),
        migrations.RemoveField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDUsuarioAlta',
        ),
        migrations.AddField(
            model_name='pagosxproveedor',
            name='IDProveedor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagosxproveedor',
            name='IDUsuarioAlta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagosxproveedor',
            name='IDUsuarioBaja',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
