# Generated by Django 2.1.13 on 2020-01-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosCuenta', '0002_auto_20200106_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDProveedor',
        ),
        migrations.RemoveField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDUsuarioAlta',
        ),
        migrations.AddField(
            model_name='pagosxproveedor',
            name='ComentarioBaja',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pagosxproveedor',
            name='FechaBaja',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pagosxproveedor',
            name='IDProveedor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagosxproveedor',
            name='RutaComprobante',
            field=models.CharField(default='www.google.com', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDPagoxFactura',
            field=models.ForeignKey(db_column='IDPagoxFactura', on_delete=django.db.models.deletion.CASCADE, to='EstadosCuenta.PagosxFacturas'),
        ),
    ]
