# Generated by Django 2.1.13 on 2020-01-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosCuenta', '0003_auto_20200106_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosxproveedor',
            name='ComentarioBaja',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pagosxproveedor',
            name='FechaBaja',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pagosxproveedor',
            name='IDUsuarioAlta',
            field=models.ForeignKey(db_column='IDUsuarioAlta', on_delete=django.db.models.deletion.CASCADE, related_name='IDUsuarioAlta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagosxproveedor',
            name='IDUsuarioBaja',
            field=models.ForeignKey(db_column='IDUsuarioBaja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IDUsuarioBaja', to=settings.AUTH_USER_MODEL),
        ),
    ]
