# Generated by Django 2.1.13 on 2020-01-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosCuenta', '0004_auto_20200106_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionpagosfacturasxproveedor',
            name='IDPagoxFactura',
            field=models.ForeignKey(db_column='IDPagoxFactura', on_delete=django.db.models.deletion.CASCADE, to='EstadosCuenta.PagosxFacturas'),
        ),
    ]
