# Generated by Django 2.1.13 on 2020-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('IDTransportista', models.AutoField(primary_key=True, serialize=False)),
                ('NombreComercial', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'AdmonTransportistas',
                'managed': False,
            },
        ),
    ]
