# Generated by Django 2.1.13 on 2020-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='View_Master_Proveedor',
            fields=[
                ('IDPendienteEnviar', models.IntegerField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=10, unique=True)),
                ('NombreCortoCliente', models.CharField(max_length=100)),
                ('NombreCortoProveedor', models.CharField(max_length=100)),
                ('FechaDescarga', models.DateTimeField()),
                ('Moneda', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=15)),
                ('IsEvidenciaDigital', models.BooleanField()),
                ('IsEvidenciaFisica', models.BooleanField()),
                ('Proyecto', models.CharField(max_length=30)),
                ('TipoConcepto', models.CharField(max_length=30)),
                ('IsControlDesk', models.BooleanField()),
                ('CostoSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IsFacturaProveedor', models.BooleanField()),
                ('FolioFactProveedor', models.CharField(max_length=50)),
                ('MOP', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IsFacturaCliente', models.BooleanField()),
                ('FolioFactCliente', models.CharField(max_length=50)),
                ('IDProveedor', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'View_Master_Proveedor',
                'managed': False,
            },
        ),
    ]
