# Generated by Django 2.1.13 on 2020-01-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmon', '0002_proveedor'),
        ('PendientesEnviar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ext_PendienteEnviar_Costo',
            fields=[
                ('IDPendienteEnviar', models.OneToOneField(db_column='IDPendienteEnviar', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PendientesEnviar.PendientesEnviar')),
                ('CostoSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IsFacturaProveedor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ext_PendienteEnviar_Costo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ext_PendienteEnviar_Precio',
            fields=[
                ('IDPendienteEnviar', models.OneToOneField(db_column='IDPendienteEnviar', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PendientesEnviar.PendientesEnviar')),
                ('PrecioSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioServicios', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IsFacturaCliente', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ext_PendienteEnviar_Precio',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='relacionfacturaproveedorxpartidas',
            name='IDConcepto',
        ),
        migrations.RemoveField(
            model_name='relacionfacturaproveedorxpartidas',
            name='IDUsuarioAlta',
        ),
        migrations.RemoveField(
            model_name='relacionfacturaproveedorxpartidas',
            name='IDUsuarioBaja',
        ),
        migrations.AddField(
            model_name='facturasxproveedor',
            name='IDUsuarioAlta',
            field=models.ForeignKey(db_column='IDUsuarioAlta', default=2881, on_delete=django.db.models.deletion.CASCADE, related_name='IDUsuarioAltaFactura', to='usersadmon.AdmonUsuarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturasxproveedor',
            name='IDUsuarioBaja',
            field=models.ForeignKey(db_column='IDUsuarioBaja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IDUsuarioBajaFactura', to='usersadmon.AdmonUsuarios'),
        ),
        migrations.AddField(
            model_name='relacionfacturaproveedorxpartidas',
            name='IDPendienteEnviar',
            field=models.ForeignKey(db_column='IDPendienteEnviar', default=1, on_delete=django.db.models.deletion.CASCADE, to='PendientesEnviar.PendientesEnviar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relacionfacturaproveedorxpartidas',
            name='IDFacturaxProveedor',
            field=models.ForeignKey(db_column='IDFacturaxProveedor', on_delete=django.db.models.deletion.CASCADE, related_name='FacturaxPartidas', to='PendientesEnviar.FacturasxProveedor'),
        ),
    ]
