# Generated by Django 2.1.13 on 2019-12-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PendientesEnviar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionfacturaproveedorxpartidas',
            name='IDFacturaxProveedor',
            field=models.ForeignKey(db_column='IDFacturaxProveedor', on_delete=django.db.models.deletion.CASCADE, to='PendientesEnviar.FacturasxProveedor'),
        ),
    ]
