# Generated by Django 2.1.13 on 2020-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendientesEnviar', '0002_auto_20200109_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasxproveedor',
            name='IDProveedor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facturasxproveedor',
            name='Folio',
            field=models.CharField(max_length=50),
        ),
    ]
