# Generated by Django 2.1.13 on 2019-12-16 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PendientesEnviar', '0002_auto_20191209_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ext_PendienteEnviar_Costo',
            fields=[
                ('IDPendienteEnviar', models.OneToOneField(db_column='IDPendienteEnviar', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PendientesEnviar.PendientesEnviar')),
                ('CostoSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IsFacturaProveedor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ext_PendienteEnviar_Costo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ext_PendienteEnviar_Precio',
            fields=[
                ('IDPendienteEnviar', models.OneToOneField(db_column='IDPendienteEnviar', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PendientesEnviar.PendientesEnviar')),
                ('PrecioSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioServicios', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IsFacturaCliente', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ext_PendienteEnviar_Precio',
                'managed': False,
            },
        ),
    ]
